version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 ../src-helpdesk-business-hours-api.zip .
      - zip -g src-helpdesk-business-hours-api.zip *.py 
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name hours-of-operation-tool --zip-file fileb://src-helpdesk-business-hours-api.zip
